name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t02-01-01
      id: t02-01-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-01-01
        setup-command: make compile
        command: make -s test_01
        input: |-
          3
          5000
        expected-output: |
          ---
          15000.00
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t02-01-02
      id: t02-01-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-01-02
        setup-command: make compile
        command: make -s test_01
        input: |-
          15
          10000
        expected-output: |
          15000.00
          135000.00
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t02-01-03
      id: t02-01-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-01-03
        setup-command: make compile
        command: make -s test_01
        input: |-
          50
          50000
        expected-output: |
          375000.00
          2125000.00
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t02-01-04
      id: t02-01-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-01-04
        setup-command: make compile
        command: make -s test_01
        input: |-
          10
          10000
        expected-output: |
          10000.00
          90000.00
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t02-02-01
      id: t02-02-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-01
        setup-command: make compile
        command: make -s test_02
        input: '1'
        expected-output: |
          staple food
          you need side dishes
        comparison-method: exact
        timeout: 1
        max-score: 4
    - name: t02-02-02
      id: t02-02-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-02
        setup-command: make compile
        command: make -s test_02
        input: '2'
        expected-output: |
          side dishes
          staple food
          you need vegetables
        comparison-method: exact
        timeout: 1
        max-score: 4
    - name: t02-02-03
      id: t02-02-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-03
        setup-command: make compile
        command: make -s test_02
        input: '3'
        expected-output: |
          vegetables
          side dishes
          staple food
          good
        comparison-method: exact
        timeout: 1
        max-score: 4
    - name: t02-02-04
      id: t02-02-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-04
        setup-command: make compile
        command: make -s test_02
        input: '4'
        expected-output: |
          fruits
          vegetables
          side dishes
          staple food
          very good
        comparison-method: exact
        timeout: 1
        max-score: 4
    - name: t02-02-05
      id: t02-02-05
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-05
        setup-command: make compile
        command: make -s test_02
        input: '5'
        expected-output: |
          milk
          fruits
          vegetables
          side dishes
          staple food
          perfect
        comparison-method: exact
        timeout: 1
        max-score: 4
    - name: t03-03-01
      id: t03-03-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-03-01
        setup-command: make compile
        command: make -s test_03
        input: |-
          +
          1
          2
          3
          4
        expected-output: |
          1
          3
          6
          10
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t03-03-02
      id: t03-03-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-03-02
        setup-command: make compile
        command: make -s test_03
        input: |-
          -
          2
          3
          4
          5
        expected-output: |
          2
          1
          3
          2
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t03-03-03
      id: t03-03-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-03-03
        setup-command: make compile
        command: make -s test_03
        input: |-
          *
          1
          2
          3
          4
        expected-output: |
          1
          2
          6
          24
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t03-03-04
      id: t03-03-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t03-03-04
        setup-command: make compile
        command: make -s test_03
        input: |-
          +
          -1
        expected-output: '0

          '
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T02-01-01_RESULTS: "${{steps.t02-01-01.outputs.result}}"
        T02-01-02_RESULTS: "${{steps.t02-01-02.outputs.result}}"
        T02-01-03_RESULTS: "${{steps.t02-01-03.outputs.result}}"
        T02-01-04_RESULTS: "${{steps.t02-01-04.outputs.result}}"
        T02-02-01_RESULTS: "${{steps.t02-02-01.outputs.result}}"
        T02-02-02_RESULTS: "${{steps.t02-02-02.outputs.result}}"
        T02-02-03_RESULTS: "${{steps.t02-02-03.outputs.result}}"
        T02-02-04_RESULTS: "${{steps.t02-02-04.outputs.result}}"
        T02-02-05_RESULTS: "${{steps.t02-02-05.outputs.result}}"
        T03-03-01_RESULTS: "${{steps.t03-03-01.outputs.result}}"
        T03-03-02_RESULTS: "${{steps.t03-03-02.outputs.result}}"
        T03-03-03_RESULTS: "${{steps.t03-03-03.outputs.result}}"
        T03-03-04_RESULTS: "${{steps.t03-03-04.outputs.result}}"
      with:
        runners: t02-01-01,t02-01-02,t02-01-03,t02-01-04,t02-02-01,t02-02-02,t02-02-03,t02-02-04,t02-02-05,t03-03-01,t03-03-02,t03-03-03,t03-03-04
